---
name: cache-trunk
on:
  push:
    branches: [main]
    paths: [.trunk/trunk.yaml]

permissions: read-all

jobs:
  cache-trunk:
    name: cache-trunk
    runs-on: ubuntu-latest
    permissions:
      actions: write

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: populate-cache
        uses: trunk-io/trunk-action@v1
        with:
          check-mode: populate_cache_only
