---
name: cache-trunk
on:
  push:
    branches: [main]
    paths: [.trunk/trunk.yaml]

permissions: read-all

jobs:
  cache-trunk:
    name: cache-trunk
    runs-on: ubuntu-latest
    permissions:
      actions: write

    steps:
      - name: checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: populate-cache
        uses: trunk-io/trunk-action@86b68ffae610a05105e90b1f52ad8c549ef482c2 # v1
        with:
          check-mode: populate_cache_only
