---
name: cache-trunk
on:
  push:
    branches: [main]
    paths: [.trunk/trunk.yaml]

permissions: read-all

jobs:
  cache-trunk:
    name: cache-trunk
    runs-on: ubuntu-latest
    permissions:
      actions: write

    steps:
      - name: checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: populate-cache
        uses: trunk-io/trunk-action@12da16fcdd5cad1903d0082e591e09df7b67c7f0 # v1
        with:
          check-mode: populate_cache_only
